### ISSUE TITLE
Google Play Protect flagging app as harmful

### ISSUE THREAD

**Issue by coderkei** [ismartcoding/plain-app#191]
**Describe the bug**
Google play protect is flagging this app as harmful

**To Reproduce**
1. Install or update the app directly from github releases with play protect enabled.
2. The message will appear. This will also show as a notification.

**Expected behavior**
For this to not occur, presumably its a false positive but still a concern

**Screenshots**
![Screenshot_20240701_225538_Google Play Store](https://github.com/ismartcoding/plain-app/assets/7037851/4845a8b8-e5fb-4cf7-ae5d-b18c766bef38)

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21
 - OS: Android 14
 - App Version: 1.3.3

**Additional context**
Any idea why its being flagged? I assume its a false positive. Not sure if the F-Droid build is affected as this was with the github release build.

**Comment by ismartcoding** [comment]
The issue was resolved after rebuilding the APK. (root cause is still unknown)

**Comment by ismartcoding** [comment]
I believe Google Play Protect utilizes results from multiple file scanning platforms.
It's absurd that some file scanning platforms label apps as malicious based solely on the permissions they request.

![image](https://github.com/ismartcoding/plain-app/assets/92670034/46335fdf-0e3d-4b51-b101-675d72cdbf47)

![image](https://github.com/ismartcoding/plain-app/assets/92670034/4ba3c678-0b85-430b-8676-37cf3ea49a01)

**Comment by torbato** [comment]
So if we are using the Github release version we can just ignore the flagging? I tried uninstalling and reinstalling multiple times but the bug is still present but I still want to be on the latest version since the one packaged for f-droid is older.

**Comment by ismartcoding** [comment]
Version 1.3.4 is identical to 1.3.3; the only change made was an increase in version number to test Google Protect.
